apiVersion: v2
name: calcom
description: Deploy Calcom in a Helm Chart
type: application
version: 0.9.1
appVersion: v5.4.16
keywords:
  - kubernetes
  - chart
  - schedule
  - conference
  - calendar
  - visio
  - helm
  - meeting
  - cal
  - appointment
  - calcom
sources:
  - https://github.com/luroden/calcom-helm
home: https://luroden.github.io/calcom-helm/
maintainers:
  - name: luroden
    url: https://github.com/luroden/calcom-helm
